### ISSUE TITLE
Back End

### ISSUE THREAD

**Issue by HemaSAli** [FACG5/AE-News#3]
- [x] server.js
    - [x] create server with its port and hots
- [x] router.js
    - [x] routing home page
    - [x] route to get Data from Api (/get) 
    - [x] route 404 error page 
- [x] function.js
   - [x] get data from Api 
   - [x] handling each routes
